# Generated by Django 3.1.7 on 2021-03-01 12:25

from django.db import migrations, models
import django.db.models.deletion
import service_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPriorities',
            fields=[
                ('area_type', service_admin.models.VarCharField(max_length=15, primary_key=True, serialize=False)),
                ('priority', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'covid19\".\"area_priorities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('area_type', service_admin.models.VarCharField(max_length=15)),
                ('area_code', service_admin.models.VarCharField(max_length=12)),
                ('area_name', service_admin.models.VarCharField(max_length=120)),
            ],
            options={
                'db_table': 'covid19\".\"area_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeoReference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', service_admin.models.VarCharField(max_length=50)),
                ('geometry_type', service_admin.models.VarCharField(max_length=50)),
                ('coordinates', models.JSONField()),
            ],
            options={
                'db_table': 'covid19\".\"geo_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetricReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric', service_admin.models.VarCharField(max_length=120, unique=True)),
                ('metric_name', service_admin.models.VarCharField(max_length=150, null=True, blank=False)),
                ('released', models.BooleanField()),
            ],
            options={
                'db_table': 'covid19\".\"metric_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostcodeLookup',
            fields=[
                ('postcode', service_admin.models.VarCharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'covid19\".\"postcode_lookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', service_admin.models.VarCharField(max_length=50)),
                ('file_path', service_admin.models.VarCharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'covid19\".\"processed_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'covid19\".\"processing_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(unique=True)),
                ('released', models.BooleanField()),
            ],
            options={
                'db_table': 'covid19\".\"release_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('hash', service_admin.models.VarCharField(max_length=24, primary_key=True, serialize=False)),
                ('partition_id', service_admin.models.VarCharField(max_length=26)),
                ('date', models.DateField()),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'covid19\".\"time_series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReleaseCategory',
            fields=[
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='service_admin.releasereference')),
                ('process_name', service_admin.models.VarCharField(choices=[('MAIN', 'MAIN'), ('MSOA:CASES', 'MSOA:CASES'), ('DEMOGRAPHICS:DEATHS', 'DEMOGRAPHICS:DEATHS'), ('DEMOGRAPHICS:CASES', 'DEMOGRAPHICS:CASES')], max_length=50)),
            ],
            options={
                'db_table': 'covid19\".\"release_category',
                'managed': False,
            },
        ),
    ]
