# Generated by Django 3.1.7 on 2021-03-01 13:10

from django.db import migrations, models
import service_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0004_create_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', service_admin.models.VarCharField(max_length=255)),
                ('methodology', models.TextField()),
            ],
            options={
                'db_table': 'covid19\".\"methodology',
            },
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.methodology')"
        ),
    ]
