# Generated by Django 3.1.7 on 2021-03-01 13:11

from django.db import migrations, models
import django.db.models.deletion
import service_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0005_create_methodology'),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'sequential';"
        ),
        migrations.CreateModel(
            name='MetricDocumentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_frequency', service_admin.models.VarCharField(
                    choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly'),
                             ('MONTHLY', 'Monthly')], max_length=255)),
                ('abstract',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.abstract')),
                ('description',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.description')),
                ('methodology',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.methodology')),
                ('metric_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation',
                                   to='service_admin.metricreference')),
                ('source', models.ManyToManyField(to='service_admin.DataSource')),
            ],
            options={
                'db_table': 'covid19\".\"metric_documentation',
            },
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.metric_documentation_source')"
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.metric_documentation')"
        ),
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'parallel';"
        ),
    ]
