# Generated by Django 3.1.7 on 2021-03-01 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('service_admin', '0006_create_metric_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OversightRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='object id')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('activity', models.CharField(choices=[('C', 'Created'), ('M', 'Modified'), ('R', 'Reviewed')], db_index=True, editable=False, max_length=1, verbose_name='activity')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'activity log',
                'verbose_name_plural': 'activity logs',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='content_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', 'user'], name='content_by_user_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp'], name='recent_content_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', 'activity', 'user'], name='content_user_activity_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp', 'user'], name='recent_user_content_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp', 'activity'], name='recent_content_activities_idx'),
        ),
        migrations.AddConstraint(
            model_name='oversightrecord',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, activity='M'), fields=('content_type', 'object_id', 'activity', 'user'), name='content_user_activity_unique_non_modifier'),
        ),
    ]
