# Generated by Django 3.1.7 on 2021-03-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0007_auto_20210301_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL name for the service: This is utilised to construct the URL for service admin and the API. May only contain characters, numbers, - (hyphen) or _ (underscore).', unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('pk',),
            },
        ),
        migrations.RemoveIndex(
            model_name='oversightrecord',
            name='content_idx',
        ),
        migrations.RemoveIndex(
            model_name='oversightrecord',
            name='content_by_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='oversightrecord',
            name='recent_content_idx',
        ),
        migrations.RemoveIndex(
            model_name='oversightrecord',
            name='content_user_activity_idx',
        ),
        migrations.RemoveIndex(
            model_name='oversightrecord',
            name='recent_user_content_idx',
        ),
        migrations.RemoveIndex(
            model_name='oversightrecord',
            name='recent_content_activities_idx',
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id'], name='oversight_cnt_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', 'user'], name='oversight_usercnt_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp'], name='oversight_recent_objcnt_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', 'activity', 'user'], name='oversight_recent_useract_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp', 'user'], name='oversight_recent_timecnt_idx'),
        ),
        migrations.AddIndex(
            model_name='oversightrecord',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp', 'activity'], name='oversight_recent_objact_idx'),
        ),
        migrations.AddField(
            model_name='service',
            name='oversight_records',
            field=models.ManyToManyField(db_index=True, related_name='service_records', to='service_admin.OversightRecord', verbose_name='oversight records'),
        ),
    ]
