# Generated by Django 3.1.7 on 2021-03-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0009_auto_20210301_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodology',
            options={'verbose_name_plural': 'Methodologies'},
        ),
        migrations.AlterModelOptions(
            name='timeseries',
            options={'managed': False, 'verbose_name_plural': 'time series'},
        ),
        migrations.AlterField(
            model_name='metricdocumentation',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='service_admin.metricreference', verbose_name='Metric'),
        ),
    ]
