# Generated by Django 3.1.7 on 2021-03-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0013_pageuri_yellowbanner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YellowBanner',
            new_name='Announcement',
        ),
    ]
