# Generated by Django 3.1.7 on 2021-03-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0014_auto_20210304_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
