# Generated by Django 3.1.7 on 2021-03-04 18:30

from django.db import migrations, models
import markdownx.models
import service_admin.models.fields
import service_admin.utils.default_generators


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0015_delete_announcement'),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'sequential';"
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', service_admin.models.fields.VarCharField(default=service_admin.utils.default_generators.generate_unique_id, max_length=36, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('appear_by_update', models.DateField(verbose_name='appear by update')),
                ('disappear_by_update', models.DateField(verbose_name='disappear by update')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('body', markdownx.models.MarkdownxField(verbose_name='body')),
                ('relative_urls', models.ManyToManyField(to='service_admin.PageURI')),
            ],
            options={
                'db_table': 'covid19"."announcement',
            },
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.announcement_relative_urls')"
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.announcement')"
        ),
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'parallel';"
        ),
    ]
