# Generated by Django 3.1.7 on 2021-03-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0016_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='applicable_to',
        ),
        migrations.RemoveField(
            model_name='metricdocumentation',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='metricdocumentation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='metricdocumentation',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='metricdocumentation',
            name='metric_id',
        ),
        migrations.RemoveField(
            model_name='metricdocumentation',
            name='source',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement'},
        ),
        migrations.AlterModelOptions(
            name='areapriorities',
            options={'managed': False, 'permissions': [('create_area_priorities_object', 'Can create metrics'), ('manage_area_priorities_object', 'Can manage metrics'), ('view_area_priorities_object', 'Can view metrics'), ('delete_area_priorities_object', 'Can delete metrics')]},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('pk',), 'permissions': (('manage_service_object', 'Can manage service'), ('view_service_object', 'Can view service'), ('create_metric_object', 'Can create metrics'), ('manage_metric_object', 'Can manage metrics'), ('view_metric_object', 'Can view metrics'), ('view_delete_object', 'Can delete metrics'), ('manage_release_object', 'Can despatch data'), ('view_release_object', 'Can view despatch'), ('create_banner_object', 'Can manage banners'), ('manage_banner_object', 'Can manage banners'), ('view_banner_object', 'Can view banners'), ('create_changelog_object', 'Can create change logs'), ('manage_changelog_object', 'Can manage change logs'), ('view_changelog_object', 'Can view change logs'), ('create_metricdoc_object', 'Can create metric documentations'), ('manage_metricdoc_object', 'Can manage metric documentations'), ('view_metricdoc_object', 'Can view metric documentations')), 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.DeleteModel(
            name='Abstract',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Methodology',
        ),
        migrations.DeleteModel(
            name='MetricDocumentation',
        ),
    ]
