# Generated by Django 3.1.7 on 2021-03-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0018_datasource_description_methodology_metricabstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='methodology',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricabstract',
            name='metric',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Methodology',
        ),
        migrations.DeleteModel(
            name='MetricAbstract',
        ),
    ]
