# Generated by Django 3.1.7 on 2021-03-06 00:44

from django.db import migrations, models
import django.db.models.deletion
import service_admin.models.fields
import service_admin.utils.default_generators


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0019_auto_20210305_2331'),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'sequential';"
        ),
        migrations.CreateModel(
            name='MetricAsset',
            fields=[
                ('id', service_admin.models.fields.VarCharField(default=service_admin.utils.default_generators.generate_unique_id, max_length=36, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('label', service_admin.models.fields.VarCharField(max_length=255)),
                ('asset_type', service_admin.models.fields.VarCharField(choices=[('ABSTRACT', 'Abstract'), ('DESCRIPTION', 'Description'), ('METHODOLOGY', 'Methodology')], db_index=True, max_length=50)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'covid19"."metric_asset',
            },
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.metric_asset')"
        ),
        migrations.CreateModel(
            name='MetricAssetToMetric',
            fields=[
                ('id', service_admin.models.fields.VarCharField(default=service_admin.utils.default_generators.generate_unique_id, max_length=36, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.metricasset')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.metricreference')),
            ],
            options={
                'db_table': 'covid19"."metric_asset_to_metric',
            },
        ),
        migrations.RunSQL(
            "SELECT create_distributed_table('covid19.metric_asset_to_metric', 'id')"
        ),
        migrations.RunSQL("""
          ALTER TABLE covid19.metric_asset_to_metric
          DROP CONSTRAINT metric_asset_to_metric_pkey CASCADE;
    
          ALTER TABLE covid19.metric_asset_to_metric
          ADD CONSTRAINT myapp_manager_pkey
          PRIMARY KEY (metric_id, id);
        """),
        migrations.AddField(
            model_name='metricasset',
            name='metric',
            field=models.ManyToManyField(through='service_admin.MetricAssetToMetric', to='service_admin.MetricReference'),
        ),
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'parallel';"
        ),
    ]
