# Generated by Django 3.1.7 on 2021-03-06 10:21

from django.db import migrations
import service_admin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0021_auto_20210306_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricasset',
            name='asset_type',
        ),
        migrations.AddField(
            model_name='metricassettometric',
            name='asset_type',
            field=service_admin.models.fields.VarCharField(choices=[('ABSTRACT', 'Abstract'), ('DESCRIPTION', 'Description'), ('METHODOLOGY', 'Methodology')], db_index=True, default='ABSTRACT', max_length=50),
            preserve_default=False,
        ),
    ]
