# Generated by Django 3.1.7 on 2021-03-06 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0022_auto_20210306_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricasset',
            name='metric',
        ),
        migrations.DeleteModel(
            name='MetricAssetToMetric',
        ),
    ]
