# Generated by Django 3.1.7 on 2021-03-07 10:06

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import service_admin.models.fields
import service_admin.utils.default_generators


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0024_metric_asset_to_metric'),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'sequential';"
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=service_admin.utils.default_generators.generate_unique_id, editable=False, max_length=36, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('association', service_admin.models.fields.VarCharField(max_length=30)),
                ('tag', service_admin.models.fields.VarCharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'covid19"."tag',
            },
        ),
        migrations.RunSQL(
            "SELECT create_distributed_table('covid19.tag', 'id')"
        ),
        migrations.CreateModel(
            name='MetricTag',
            fields=[
                ('id', models.UUIDField(default=service_admin.utils.default_generators.generate_unique_id, max_length=36, editable=False, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.metricreference', to_field='metric')),
                ('tag', models.ForeignKey(limit_choices_to={'association': 'METRICS'}, on_delete=django.db.models.deletion.CASCADE, to='service_admin.tag')),
            ],
            options={
                'db_table': 'covid19"."metric_tag',
            },
        ),
        migrations.RunSQL("""
          ALTER TABLE covid19.metric_tag
          DROP CONSTRAINT metric_tag_pkey CASCADE;
        
          ALTER TABLE covid19.metric_tag
          ADD CONSTRAINT metric_tag_pkey
          PRIMARY KEY (tag_id, metric_id, id);
        """),
        migrations.RunSQL(
            "SELECT create_distributed_table('covid19.metric_tag', 'tag_id')"
        ),
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'parallel';"
        ),
    ]
