# Generated by Django 3.1.7 on 2021-03-07 11:09

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields
import service_admin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0025_auto_20210307_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricreference',
            options={'verbose_name': 'metric'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='association',
            field=service_admin.models.fields.VarCharField(choices=[('METRICS', 'Metrics'), ('LOGS', 'Logs')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='metrictag',
            unique_together={('tag', 'id')},
        ),
    ]
