# Generated by Django 3.1.7 on 2021-03-08 00:26

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import markdownx.models
import service_admin.models.fields
import service_admin.models.page
import service_admin.utils.default_generators


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0026_auto_20210307_1109'),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'sequential';"
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=service_admin.utils.default_generators.generate_unique_id, editable=False, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('title', service_admin.models.fields.VarCharField(max_length=120, db_index=True, unique=True)),
                ('uri', service_admin.models.fields.VarCharField(max_length=150, validators=[service_admin.models.page.url_validator])),
            ],
            options={
                'verbose_name': 'page',
                'db_table': 'covid19"."page',
            },
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.page')"
        ),
        migrations.AlterModelOptions(
            name='metricreference',
            options={'managed': False, 'verbose_name': 'metric'},
        ),
        migrations.AlterModelOptions(
            name='metrictag',
            options={'ordering': ('metric', '-tag')},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='relative_urls',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body',
            field=markdownx.models.MarkdownxField(max_length=200, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.UUIDField(default=service_admin.utils.default_generators.generate_unique_id, editable=False, primary_key=True, serialize=False, verbose_name='unique ID'),
        ),
        # migrations.CreateModel(
        #     name='BannerPage',
        #     fields=[
        #         ('id', models.UUIDField(default=service_admin.utils.default_generators.generate_unique_id, editable=False, primary_key=True, serialize=False, verbose_name='unique ID')),
        #         ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.announcement')),
        #         ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.page')),
        #     ],
        #     options={
        #         'verbose_name': 'banner page',
        #         'db_table': 'covid19"."banner_page',
        #         'managed': False
        #     },
        # ),
        # migrations.RunSQL(
        #     "SELECT create_reference_table('covid19.banner_page')"
        # ),
        # migrations.AddField(
        #     model_name='announcement',
        #     name='pages',
        #     field=models.ManyToManyField(through='service_admin.BannerPage', to='service_admin.Page'),
        # ),
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'parallel';"
        ),
    ]
