# Generated by Django 3.1.7 on 2021-03-08 00:32

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0027_auto_20210308_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='appear_by_update',
            field=models.DateField(db_index=True, verbose_name='appear by update'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='disappear_by_update',
            field=models.DateField(db_index=True, verbose_name='disappear by update'),
        )
    ]
