# Generated by Django 3.1.7 on 2021-03-10 19:35

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0028_auto_20210308_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseStats',
            fields=[
                ('release_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='service_admin.releasereference')),
                ('record_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Release statistic',
                'verbose_name_plural': 'Release statistics',
                'db_table': 'covid19"."release_stats',
                'managed': False,
            },
        )
    ]
