# Generated by Django 3.1.7 on 2021-03-17 09:57

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import service_admin.models.fields
import service_admin.utils.default_generators


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0029_auto_20210310_1935'),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'sequential';"
        ),
        migrations.CreateModel(
            name='MetricETLReference',
            fields=[
                ('id', service_admin.models.fields.VarCharField(default=service_admin.utils.default_generators.generate_unique_id, max_length=36, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('missing_to_zero', models.BooleanField(default=False)),
                ('fill_forward', models.BooleanField(default=False)),
                ('negative_to_zero', models.BooleanField(default=False)),
                ('prevalence_rate', models.BooleanField(default=False)),
                ('incidence_rate', models.BooleanField(default=False)),
                ('ratio_to_percentage', models.BooleanField(default=False)),
                ('rolling_sum_direction', models.BooleanField(default=False)),
                ('metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_admin.metricreference')),
            ],
            options={
                'verbose_name': 'ETL Metric',
                'verbose_name_plural': 'ETL Metrics',
                'db_table': 'covid19"."metric_etl_reference',
            },
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.metric_etl_reference');"
        ),
        migrations.RunSQL(
            "SET LOCAL citus.multi_shard_modify_mode TO 'parallel';"
        ),
    ]
