# Generated by Django 3.1.7 on 2021-04-08 12:17

from django.db import migrations, models
import service_admin.utils.default_generators


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0031_auto_20210408_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArea',
            fields=[
                ('id', models.UUIDField(default=service_admin.utils.default_generators.generate_unique_id, editable=False, primary_key=True, serialize=False, verbose_name='unique ID')),
            ],
            options={
                'verbose_name': 'banner area',
                'db_table': 'covid19"."banner_area',
                'managed': False,
            },
        ),
    ]
