# Generated by Django 3.1.7 on 2021-04-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0032_bannerarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areareference',
            options={'managed': False, 'ordering': ['area_type', '-area_name'], 'verbose_name': 'area'},
        ),
    ]
