# Generated by Django 3.1.7 on 2021-06-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0033_auto_20210408_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricetlreference',
            options={'managed': False, 'verbose_name': 'ETL Metric', 'verbose_name_plural': 'ETL Metrics'},
        ),
    ]
