# Generated by Django 3.1.7 on 2021-06-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0035_bannertag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricasset',
            options={'managed': False, 'ordering': ('label',)},
        ),
        migrations.AlterModelOptions(
            name='metricassettometric',
            options={'managed': False, 'ordering': ('metric', 'asset', 'order'), 'verbose_name': 'asset association'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'managed': False, 'verbose_name': 'page'},
        ),
    ]
