# Generated by Django 3.2.5 on 2021-07-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0037_changelog_changelogtometric_changelogtopage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ('-date',)},
        ),
    ]
