# Generated by Django 3.2.5 on 2021-07-16 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0038_alter_changelog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='area',
            field=models.ManyToManyField(related_name='log_areas', to='service_admin.AreaReference'),
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.change_log_area')"
        ),
    ]
