# Generated by Django 3.2.5 on 2021-07-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0039_auto_20210716_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areareference',
            options={'managed': False, 'ordering': ['area_type', 'area_code'], 'verbose_name': 'area'},
        ),
        migrations.AlterModelOptions(
            name='changelog',
            options={'managed': False, 'ordering': ('-date',)},
        ),
    ]
