# Generated by Django 3.2.5 on 2021-08-29 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0042_auto_20210807_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='unique ID')),
                ('label', models.CharField(db_index=True, max_length=64, verbose_name='label')),
                ('slug', models.SlugField(help_text='URL name for the content: This is utilised to construct the URL for service admin and the API. May only contain characters, numbers, - (hyphen) or _ (underscore).')),
                ('child_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='service_admin.content', verbose_name='child of')),
                ('page', models.ForeignKey(limit_choices_to={'data_category': True}, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='service_admin.page', verbose_name='section')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
                'db_table': 'covid19"."cms_content',
                'ordering': ('pk',),
            },
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.cms_content')"
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('value', models.TextField(verbose_name='value')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='service_admin.content')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
                'db_table': 'covid19"."cms_entry',
                'ordering': ('content', 'order'),
            },
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.cms_entry')"
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='name')),
                ('identifier', models.CharField(db_index=True, max_length=16, verbose_name='identifier')),
                ('type', models.CharField(choices=[('ST', 'Short text (<256 characters)'), ('LT', 'Long text (256+ characters)'), ('IM', 'Image'), ('FL', 'File'), ('MA', 'Marker'), ('MD', 'Markdown'), ('RT', 'Rich Text (HTML)'), ('LC', 'Link to another page')], db_index=True, max_length=2, verbose_name='field type')),
                ('meta_fields', models.JSONField(blank=True, default=dict, verbose_name='meta fields')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'db_table': 'covid19"."cms_field',
            },
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('covid19.cms_field')"
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'managed': False, 'ordering': ['-launch', '-expire'], 'verbose_name': 'Announcement'},
        ),
        migrations.AddField(
            model_name='entry',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_field', to='service_admin.field', verbose_name='field'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['content', 'order'], name='ordered_entries'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['page', 'slug'], name='section_content_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['page', 'label'], name='section_content_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('label', 'page', 'child_of'), ('slug', 'page')},
        ),
    ]
