# Generated by Django 3.2.5 on 2021-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0046_auto_20210902_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualisationfield',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='visualisationfield',
            name='rolling_average',
        ),
        migrations.RemoveField(
            model_name='tab',
            name='fields',
        ),
        migrations.DeleteModel(
            name='TabulationField',
        ),
        migrations.DeleteModel(
            name='VisualisationField',
        ),
    ]
