# Generated by Django 3.2.5 on 2021-09-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0048_auto_20210902_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='fields',
            field=models.ManyToManyField(db_table='cms"."tab_to_tab_fields', related_name='fields_of', to='service_admin.TabField'),
        ),
        migrations.RunSQL(
            "SELECT create_reference_table('cms.tab_to_tab_fields')"
        ),
    ]
