# Generated by Django 3.2.5 on 2021-09-04 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0049_auto_20210903_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('colour', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'colour',
                'db_table': 'cms"."colour',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='tabulationfield',
            name='nested_metrics',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='visualisationfield',
            name='nested_metrics',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
