# Generated by Django 3.2.5 on 2021-09-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0050_auto_20210904_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='visualisationfield',
            name='colour',
        )
    ]
