# Generated by Django 3.2.5 on 2021-09-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0052_auto_20210904_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomFieldParameter',
            new_name='CustomFilterParameter',
        ),
        migrations.AlterModelOptions(
            name='customfilterparameter',
            options={'verbose_name': 'custom filter parameter'},
        ),
        migrations.AlterModelTable(
            name='customfilterparameter',
            table='cms"."custom_filter_parameter',
        )
    ]
