# Generated by Django 3.2.5 on 2021-09-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0055_auto_20210905_1314'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='service',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.DeleteModel(
        #     name='PageURI',
        # ),
        # migrations.DeleteModel(
        #     name='BannerPage',
        # ),
        # migrations.AlterField(
        #     model_name='oversightrecord',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.CreateModel(
        #     name='TabulationMetric',
        #     fields=[
        #         ('tabmetric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_admin.tabmetric')),
        #         ('tabulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabulationmetric_related', to='service_admin.tabulationfield')),
        #     ],
        #     bases=('service_admin.tabmetric',),
        #     options={
        #         'db_table': 'cms"."tabulation_metric',
        #     }
        # ),
        # migrations.RunSQL(
        #     "SELECT create_reference_table('cms.tabulation_metric')"
        # ),
        # migrations.CreateModel(
        #     name='VisualisationMetric',
        #     fields=[
        #         ('tabmetric_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_admin.tabmetric')),
        #         ('visualisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualisationmetric_related', to='service_admin.visualisationfield')),
        #     ],
        #     bases=('service_admin.tabmetric',),
        #     options={
        #         'db_table': 'cms"."visualisation_metric',
        #     }
        # ),
        # migrations.RunSQL(
        #     "SELECT create_reference_table('cms.visualisation_metric')"
        # ),
        # migrations.AlterField(
        #     model_name='tabmetric',
        #     name='colour',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabmetric_related_colours', to='service_admin.colour'),
        # ),
        # migrations.AlterField(
        #     model_name='tabmetric',
        #     name='value',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabmetric_related_tabs', to='service_admin.metricreference', to_field='metric'),
        # ),
        # migrations.AlterField(
        #     model_name='tabulationfield',
        #     name='metrics',
        #     field=models.ManyToManyField(related_name='table_of_metric', through='service_admin.TabulationMetric', to='service_admin.MetricReference'),
        # ),
        # migrations.AlterField(
        #     model_name='visualisationfield',
        #     name='metrics',
        #     field=models.ManyToManyField(related_name='visualisation_of_metric', through='service_admin.VisualisationMetric', to='service_admin.MetricReference'),
        # ),
    ]
