# Generated by Django 3.2.5 on 2021-09-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0057_auto_20210905_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabulationfield',
            name='metrics',
            field=models.ManyToManyField(related_name='table_of_metric', through='service_admin.TabulationMetric', to='service_admin.MetricReference'),
        ),
        migrations.AddField(
            model_name='visualisationfield',
            name='metrics',
            field=models.ManyToManyField(related_name='visualisation_of_metric', through='service_admin.VisualisationMetric', to='service_admin.MetricReference'),
        ),
    ]
