# Generated by Django 3.2.5 on 2021-09-06 09:21

from django.db import migrations, models
import django.db.models.deletion
from uuid import uuid4


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('service_admin', '0058_auto_20210905_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualisationmetric',
            name='tabmetric_ptr',
        ),
        migrations.RemoveField(
            model_name='visualisationmetric',
            name='visualisation',
        ),
        migrations.RemoveField(
            model_name='tabulationfield',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='visualisationfield',
            name='metrics',
        ),
        migrations.AddField(
            model_name='tabmetric',
            name='field_id',
            field=models.UUIDField(default=uuid4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabmetric',
            name='field_type',
            field=models.ForeignKey(default='', limit_choices_to={'model__in': ['VisualisationField', 'TabulationField']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabmetric',
            name='tab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='service_admin.tab'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TabulationMetric',
        ),
        migrations.DeleteModel(
            name='VisualisationMetric',
        )
    ]
