# Generated by Django 3.2.5 on 2021-09-06 09:23

from django.db import migrations, models
from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields
import markdownx.models
import service_admin.models.fields
import service_admin.models.page
import service_admin.utils.default_generators

class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0059_auto_20210906_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPage',
            fields=[
                ('id',
                 models.UUIDField(default=service_admin.utils.default_generators.generate_unique_id, editable=False,
                                  primary_key=True, serialize=False, verbose_name='unique ID')),
                ('announcement',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.announcement')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_admin.page')),
            ],
            options={
                'verbose_name': 'banner page',
                'db_table': 'covid19"."banner_page',
                'managed': False
            },
        ),
        # migrations.DeleteModel(
        #     name='PageURI',
        # ),
        # migrations.AlterField(
        #     model_name='oversightrecord',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        # migrations.AlterField(
        #     model_name='service',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
    ]
