# Generated by Django 3.2.5 on 2021-09-06 10:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0061_auto_20210906_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisationfield',
            name='amplitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visualisationfield',
            name='amplitude_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visualisationfield',
            name='bar_type',
            field=models.CharField(blank=True, choices=[('overlay', 'Overlay'), ('group', 'Group'), ('stack', 'Stack')], help_text='Only applicable to bar plots - leave blank for other types.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visualisationfield',
            name='fill',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Only applicable to line (area) plots - leave blank for other types.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='visualisationfield',
            name='highlight',
            field=models.ForeignKey(blank=True, help_text='Only applicable to bar plots - leave blanks for other types.', null=True, on_delete=django.db.models.deletion.CASCADE, to='service_admin.highlight'),
        ),
        migrations.AlterField(
            model_name='visualisationfield',
            name='metric_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visualisationfield',
            name='nested_metrics',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='visualisationfield',
            name='parameter',
            field=models.CharField(blank=True, help_text='Attribute name for the 3rd dimension.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visualisationfield',
            name='type',
            field=models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('heatmap', 'Heatmap')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
