# Generated by Django 3.2.5 on 2021-09-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0062_auto_20210906_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisationfield',
            name='rolling_average',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_admin.rollingaverage'),
        ),
    ]
