# Generated by Django 3.2.5 on 2021-09-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0063_auto_20210906_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab',
            name='fields',
        ),
    ]
