# Generated by Django 3.2.5 on 2021-09-09 12:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0064_auto_20210906_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('slug_id', models.CharField(editable=False, max_length=40, verbose_name='Slug ID')),
                ('date', models.DateField(editable=False)),
                ('value', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
            options={
                'verbose_name': 'Pre-release reports',
                'db_table': 'covid19"."private_report',
                'managed': False,
            },
        )
    ]
