# Generated by Django 3.2.5 on 2021-10-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0065_auto_20210909_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatereport',
            options={'managed': False, 'verbose_name': 'Pre-release report'},
        )
    ]
