# Generated by Django 3.2.5 on 2021-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0066_auto_20211001_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(unique=True)),
            ],
            options={
                'db_table': 'covid19"."despatch',
                'ordering': ('-timestamp',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DespatchToRelease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'covid19"."despatch_to_release',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='processedfile',
            options={'managed': False, 'ordering': ('-timestamp',)},
        ),
    ]
