# Generated by Django 3.2.5 on 2021-12-07 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0067_auto_20211002_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('date_added', models.DateTimeField(auto_created=True, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='unique ID')),
                ('recipient', models.EmailField(max_length=255, unique=True, verbose_name="Recipient's email")),
                ('note', models.TextField(help_text='May include the request, justification, or the position of the recipient.', null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Report recipient',
                'verbose_name_plural': 'Report recipients',
                'db_table': 'covid19"."report_recipient',
                'permissions': (('can_approve_report_recipient', 'Can approve report recipient'),),
                'managed': False,
            },
        ),
    ]
