# Generated by Django 3.2.5 on 2021-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_admin', '0068_auto_20211207_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportrecipient',
            options={'managed': False, 'permissions': (('can_approve_report_recipient', 'Can approve report recipient'), ('can_deactivate_report_recipient', 'Can deactivate report recipient')), 'verbose_name': 'Report recipient', 'verbose_name_plural': 'Report recipients'},
        ),
        migrations.AlterModelTable(
            name='reportrecipient',
            table='covid19"."report_recipients',
        ),
    ]
