version: '3.7'

services:
  web-admin-gh:
    build: .
    restart: always
    volumes:
      - ./app/:/app/app/
      - ./server/config/uvicorn_worker.py:/app/app/uvicorn_worker.py
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    environment:
      IS_DEV: 1
      API_ENV: DEVELOPMENT
      FLASK_ENV: DEVELOPMENT
