version: '3.7'

services:
  web-admin-gh:
    build: .
    restart: always
    volumes:
      - ./app/:/app/app/
      - ./server/config/uvicorn_worker.py:/app/app/uvicorn_worker.py
      - ./server/nginx/engine_dev.nginx:/etc/nginx/conf.d/engine.conf
    ports:
      - 5510:5000
    env_file:
      - .env.dev
    environment:
      IS_DEV: 1
      API_ENV: PRODUCTION
      FLASK_ENV: DEVELOPMENT
