# Generated by Django 3.2.5 on 2021-08-28 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('label', models.CharField(db_index=True, max_length=64, verbose_name='label')),
                ('slug', models.SlugField(help_text='URL name for the content: This is utilised to construct the URL for service admin and the API. May only contain characters, numbers, - (hyphen) or _ (underscore).')),
                ('child_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.content', verbose_name='child of')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
                'db_table': 'covid19"."cms_content',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL name for the service: This is utilised to construct the URL for service admin and the API. May only contain characters, numbers, - (hyphen) or _ (underscore).', unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'db_table': 'covid19"."cms_service',
                'ordering': ('pk',),
                'permissions': (('manage_service_object', 'Can manage service'), ('view_service_object', 'Can view service'), ('view_service_contents', 'Can view service contents'), ('create_service_contents', 'Can create service contents'), ('modify_service_contents', 'Can modify service contents'), ('review_service_contents', 'Can review service contents'), ('delete_service_contents', 'Can delete service contents')),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL name for the section: This is utilised to construct the URL for service admin and the API. May only contain characters, numbers, - (hyphen) or _ (underscore).', verbose_name='slug')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.service')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'db_table': 'covid19"."cms_section',
                'permissions': (('create_section', 'Create section'), ('release_section', 'Release section'), ('verify_section', 'Verify section')),
                'unique_together': {('slug', 'service'), ('name', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='name')),
                ('identifier', models.CharField(db_index=True, max_length=16, verbose_name='identifier')),
                ('type', models.CharField(choices=[('ST', 'Short text (<256 characters)'), ('LT', 'Long text (256+ characters)'), ('IM', 'Image'), ('FL', 'File'), ('MA', 'Marker'), ('MD', 'Markdown'), ('RT', 'Rich Text (HTML)'), ('LC', 'Link to another page')], db_index=True, max_length=2, verbose_name='field type')),
                ('meta_fields', models.JSONField(blank=True, default=dict, verbose_name='meta fields')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fields', to='cms.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'field',
                'verbose_name_plural': 'fields',
                'db_table': 'covid19"."cms_field',
                'unique_together': {('name', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='value')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='order')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='cms.content')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_field', to='cms.field', verbose_name='field')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
                'db_table': 'covid19"."cms_entry',
                'ordering': ('content', 'order'),
            },
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='cms.section', verbose_name='section'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['content', 'order'], name='ordered_entries'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['section', 'slug'], name='section_content_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['section', 'label'], name='section_content_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('slug', 'section'), ('label', 'section', 'child_of')},
        ),
    ]
