# Generated by Django 3.2.5 on 2021-08-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='content',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='field',
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='field',
            name='service',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='section',
            name='service',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
